blogging/urls.py
from django.urls import path
from blogging.views import BlogListView, BlogDetailView

urlpatterns = [
    path("", BlogListView.as_view(), name="blog_index"),
    path("posts/<int:pk>/", BlogDetailView.as_view(), name="blog_detail"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("polling/", include("polling.urls")),
    path("", include("blogging.urls")),
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
]

polling/urls.py
from django.urls import path
from polling.views import PollDetailView, PollListView

urlpatterns = [
    # path('', list_view, name="poll_index"),
    path("", PollListView.as_view(), name="poll_index"),
    path("polls/<int:pk>", PollDetailView.as_view(), name="poll_detail"),
]

blogging/models.py
from django.db import models  # <-- This is already in the file
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    published_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title


class Category(models.Model):
    name = models.CharField(max_length=128)
    description = models.TextField(blank=True)
    posts = models.ManyToManyField(Post, blank=True, related_name="categories")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

polling/models.py
from django.db import models


class Poll(models.Model):
    title = models.CharField(max_length=128)
    text = models.TextField(blank=True)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.title

blogging/views.py
from django.shortcuts import render
from django.template import loader
from django.http.response import HttpResponse, Http404
from blogging.models import Post

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


class BlogListView(ListView):
    queryset = Post.objects.order_by("-published_date").exclude(
        published_date__exact=None
    )
    template_name = "blogging/list.html"


class BlogDetailView(DetailView):
    queryset = Post.objects.order_by("-published_date").exclude(
        published_date__exact=None
    )
    template_name = "blogging/detail.html"

polling/views.py
from django.shortcuts import render
from django.http import Http404
from polling.models import Poll

from django.views.generic.list import ListView
from django.views.generic.detail import DetailView


class PollListView(ListView):
    model = Poll
    template_name = "polling/list.html"


class PollDetailView(DetailView):
    model = Poll
    template_name = "polling/detail.html"

    def post(self, request, *args, **kwargs):
        poll = self.get_object()

        if request.POST.get("vote") == "Yes":
            poll.score += 1
        else:
            poll.score -= 1
        poll.save()

        context = {"object": poll}
        return render(request, "polling/detail.html", context)


# def list_view(request):
#     context = {"polls": Poll.objects.all()}
#     return render(request, "polling/list.html", context)

blogging/templates/blogging/detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ post }}</h1>
    <p class="byline">
        Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
    </p>
    <div class="post-body">
        {{ post.text }}
    </div>
    <ul class="categories">
        {% for category in post.categories.all %}
        <li>{{ category }}</li>
        {% endfor %}
    </ul>
{% endblock %}

blogging/templates/blogging/list.html
{% extends "base.html" %}

{% block content %}

    <h1>Recent Posts</h1>
    {% comment %} Here is where the query happens {% endcomment %}
    {% for post in post_list %}
    <div class="post">
        <h2>
            <a href="{% url 'blog_detail' post.pk%}">{{ post }}</a>
        </h2>
        <p class="byline">
            Posted by {{ post.author.username }} &mdash; {{ post.published_date }}
        </p>
        <div class="post-body">
            {{ post.text }}
        </div>
        <ul class="categories">
            {% for category in post.categories.all %}
                <li>{{ category }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endfor %}
{% endblock %}

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <title>My Django Blog</title>
    <link type="text/css" rel="stylesheet" href="{%static 'django_blog.css' %}">
  </head>
  <body>
    <div id="header">  {# header begins here #}
      <ul id="control-bar">
      {% if user.is_authenticated %}
        <li>Hello {{ user.username }} </li>
        {% if user.is_staff %}<li><a href="{% url 'admin:index' %}">admin</a></li>{% endif %}
          <li><a href="{% url 'logout' %}">logout</a></li>
        {% else %}
          <li><a href="{% url 'account_login' %}">login</a></li>
      {% endif %}
      </ul>
     </div>
    <div id="container">
      <div id="content">
      {% block content %}
       [content will go here]
      {% endblock %}
      </div>
    </div>
  </body>
</html>

mysite/templates/login.html
{% extends "base.html" %}
{% block content %}
    <h1>My Blog Login</h1>
    <form action="" method="POST">{% csrf_token %}
        {{ form.as_p }}
        <p><input type="submit" value="Log In"</p>
    </form>
{% endblock %}}

polling/templates/polling/detail.html
{% extends "base.html" %}
{% block content %}
<h1>{{ object.title }}</h1>
<div class="poll-body">
    {{ object.text }}
</div>
<div class="poll-score">
    Current score: {{ object.score }}
</div>
<div class="poll-vote">
    <form method="POST">
        {% csrf_token %}
        <input type="submit" name="vote" value="Yes">
        <input type="submit" name="vote" value="No">
    </form>
</div>
{% endblock %}

polling/templates/polling/list.html
{% extends "base.html" %}
{% block content %}
<h1>Polls</h1>
{% for poll in poll_list %}
    <div class="poll">
        <h2>
            <a href="{% url 'poll_detail' poll.pk %}">{{ poll.title }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock %}